server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Otimização de entrega de arquivos
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Muito importante para SPAs em React:
        # Tenta carregar o arquivo, se não achar cai no index.html pro React Router assumir
        try_files $uri $uri/ /index.html;
    }

    # Cache de arquivos estáticos gerados pelo Vite (assets contêm hashes únicos)
    location ~* \.(?:css|js|jpg|svg|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
