import type { LabId, LogicalSignature, Timestamp, UserId } from '../../educacao-continuada/types/_shared_refs';

// ─── Enums ────────────────────────────────────────────────────────────────────

export type Probabilidade = 1 | 2 | 3 | 4 | 5;
export type Severidade = 1 | 2 | 3 | 4 | 5;
export type Deteccao = 1 | 2 | 3 | 4 | 5;

export type Nivel = 'baixo' | 'medio' | 'alto' | 'critico';

export type Categoria =
  | 'analise'
  | 'equipamento'
  | 'material'
  | 'pessoal'
  | 'processo'
  | 'seguranca'
  | 'outro';

export type Processo =
  | 'atendimento'
  | 'coleta'
  | 'transporte'
  | 'armazenamento'
  | 'analise'
  | 'pos_analitico'
  | 'liberacao'
  | 'administrativo'
  | 'rastreabilidade';

export type Status = 'aberto' | 'mitigando' | 'monitorado' | 'fechado';

export type ResultadoRevisao = 'mantido' | 'reduzido' | 'reclassificado' | 'fechado';

export type EstrategiaA = 'evitar' | 'mitigar' | 'transferir' | 'aceitar';

// ─── Value types ──────────────────────────────────────────────────────────────

/**
 * NPR thresholds (configurable per lab via labSettings in Phase 1).
 * Phase 0 hardcoded.
 */
export interface NprThresholds {
  readonly medio: number; // default 25
  readonly alto: number; // default 61
  readonly critico: number; // default 100
}

export const DEFAULT_NPR_THRESHOLDS: NprThresholds = {
  medio: 25,
  alto: 61,
  critico: 100,
};

/**
 * Ação de tratamento (append-only in tratamento.acoes[]).
 */
export interface Acao {
  readonly id: string; // UUID or timestamp-based
  readonly criadoEm: Timestamp;
  descricao: string;
  prazo: Timestamp;
  owner: string; // usuário ID ou nome
  status: 'planejada' | 'em_andamento' | 'concluida';
}

/**
 * Tratamento do risco (mutable; acoes[] é append-only).
 */
export interface Tratamento {
  estrategia: EstrategiaA;
  acoes: readonly Acao[];
  observacoes?: string;
}

/**
 * Revisão periódica (append-only in reviewHistory[]).
 */
export interface Revisao {
  readonly criadoEm: Timestamp;
  revisor: UserId;
  revisorNome?: string;
  resultado: ResultadoRevisao;
  observacoes: string;
  nprPrevio?: number; // present if resultado === 'reclassificado'
  nprNovo?: number; // present if resultado === 'reclassificado'
  probabilidadeNova?: Probabilidade; // on reclassificado
  severidadeNova?: Severidade; // on reclassificado
  deteccaoNova?: Deteccao; // on reclassificado
}

/**
 * Audit event (append-only in /risks/{id}/events/{eventId}).
 */
export interface RiskAuditEvent {
  readonly id: string; // auto-generated by trigger
  readonly timestamp: Timestamp;
  operatorId: UserId;
  tipo:
    | 'created'
    | 'updated'
    | 'softdeleted'
    | 'revisao-registrada'
    | 'vincular_nc'
    | 'vincular_capa'
    | 'aprovar_risco';
  changes?: Record<string, unknown>;
  chainHash?: string; // populated by trigger
  prevChainHash?: string;
}

/**
 * Risk entity (persisted in /labs/{labId}/risks/{riskId}).
 */
export interface Risk {
  readonly id: string;
  readonly labId: LabId;
  codigo: string; // unique per lab
  descricao: string;
  processo: Processo;
  categoria: Categoria;

  // FMEA-lite scoring
  probabilidade: Probabilidade;
  severidade: Severidade;
  deteccao: Deteccao;
  npr: number; // P × S × D; recomputed server-side
  nivel: Nivel;

  // Extended domain fields (optional — backward-compatible with existing docs)
  causaPotencial?: string;
  efeitoPotencial?: string;
  responsavel?: string; // owner/responsible person
  setor?: string; // lab sector
  evidencias?: readonly string[]; // evidence document IDs or descriptions
  eficacia?: 'pendente' | 'eficaz' | 'parcial' | 'ineficaz'; // treatment efficacy

  status: Status;
  tratamento: Tratamento;
  reviewHistory: readonly Revisao[];

  // Linked documents (forward-compatible for Phase 4 CAPA)
  linkedCAPAs?: readonly string[]; // CAPA document IDs
  linkedNCs?: readonly string[]; // NC document IDs

  /** IDs de NC vinculadas (callable `vincularNcAoRisco`). Docs legados: tratar como `[]`. */
  ncIds?: readonly string[];
  /** IDs de CAPA vinculadas (callable). Docs legados: tratar como `[]`. */
  capaIds?: readonly string[];
  planoMelhoriaId?: string;
  aprovadoPor?: string;
  aprovadoEm?: Timestamp;

  readonly logicalSignature: LogicalSignature;
  readonly criadoEm: Timestamp;
  deletadoEm: Timestamp | null;

  // For review scheduling
  reviewDate: Timestamp | null; // next scheduled review; null if fechado
}

/**
 * Input DTO for creating/updating a risk (omits server-generated fields).
 */
export type RiskInput = Omit<
  Risk,
  | 'id'
  | 'labId'
  | 'npr' // server recomputes from P × S × D
  | 'nivel' // server derives from NPR
  | 'logicalSignature'
  | 'criadoEm'
  | 'deletadoEm'
>;

/**
 * Filters for risk queries.
 */
export interface RiskFilters {
  status?: Status[];
  nivel?: Nivel[];
  nprMin?: number;
  nprMax?: number;
  probabilidade?: Probabilidade[];
  severidade?: Severidade[];
  categoria?: Categoria[];
  processo?: Processo[];
  includeDeleted?: boolean;
  searchText?: string; // searches codigo + descricao
}

/**
 * DTO for registering a review.
 */
export interface RegistrarRevisaoInput {
  riskId: string;
  revisao: Revisao;
}

/**
 * DTO for soft-deleting a risk.
 */
export interface SoftDeleteRiskInput {
  riskId: string;
  motivo: string;
}
