import admin from 'firebase-admin';
const projectId = 'hmatologia2';
if (!admin.apps.length) admin.initializeApp({ projectId });
const db = admin.firestore();
const auth = admin.auth();
const email = 'areatecnicalabclinlabclin@gmail.com';
const labId = 'labclin-riopomba';
const user = await auth.getUserByEmail(email);
console.log(`User: ${user.email} (${user.uid})`);
const userDoc = await db.collection('users').doc(user.uid).get();
console.log(`users/${user.uid} exists: ${userDoc.exists}`);
if (userDoc.exists) console.log(`labIds: ${JSON.stringify(userDoc.data().labIds)}`);
const memberDoc = await db.collection('labs').doc(labId).collection('members').doc(user.uid).get();
console.log(`labs/${labId}/members/${user.uid} exists: ${memberDoc.exists}`);
if (memberDoc.exists) console.log(`active: ${memberDoc.data().active}`);
console.log(`Claims: ${JSON.stringify(user.customClaims)}`);
