'use client'

type ReportType = 'MONTHLY_QC_SUMMARY' | 'LOT_PERFORMANCE' | 'CORRECTIVE_ACTIONS' | 'EQUIPMENT'

interface SerializedReport {
  id: string
  type: ReportType
  periodStart: string
  periodEnd: string
  scope: Record<string, unknown>
  s3Key: string | null
  generatedById: string
  generatedAt: string
  generatedBy: { name: string }
}

interface RecentReportsTableProps {
  reports: SerializedReport[]
  onView: (r: SerializedReport) => void
  onDownload: (id: string, format: 'pdf' | 'excel') => void
}

const TYPE_LABELS: Record<ReportType, string> = {
  MONTHLY_QC_SUMMARY: 'Monthly QC Summary',
  LOT_PERFORMANCE: 'Lot Performance',
  CORRECTIVE_ACTIONS: 'Corrective Actions',
  EQUIPMENT: 'Equipment',
}

function formatDate(iso: string) {
  const d = new Date(iso)
  return d.toLocaleDateString('pt-BR', { day: '2-digit', month: '2-digit', year: 'numeric' })
}

function formatPeriod(start: string, end: string) {
  return `${formatDate(start)} – ${formatDate(end)}`
}

export function RecentReportsTable({ reports, onView, onDownload }: RecentReportsTableProps) {
  const displayed = reports.slice(0, 20)

  if (displayed.length === 0) {
    return (
      <div className="flex flex-col gap-3">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-outline">Recent Reports</h2>
        <p className="text-sm text-outline">No reports generated yet.</p>
      </div>
    )
  }

  return (
    <div className="flex flex-col gap-3">
      <h2 className="text-sm font-semibold uppercase tracking-wider text-outline">Recent Reports</h2>
      <div className="overflow-x-auto rounded border border-border">
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-surface-variant text-left">
              <th className="px-4 py-3 font-semibold text-xs uppercase tracking-wider text-outline">Generated</th>
              <th className="px-4 py-3 font-semibold text-xs uppercase tracking-wider text-outline">Type</th>
              <th className="px-4 py-3 font-semibold text-xs uppercase tracking-wider text-outline">Period</th>
              <th className="px-4 py-3 font-semibold text-xs uppercase tracking-wider text-outline">Generated By</th>
              <th className="px-4 py-3 font-semibold text-xs uppercase tracking-wider text-outline">Actions</th>
            </tr>
          </thead>
          <tbody>
            {displayed.map((report) => (
              <tr key={report.id} className="border-t border-border hover:bg-surface-variant/50 transition-colors">
                <td className="px-4 py-3 font-mono text-xs">{formatDate(report.generatedAt)}</td>
                <td className="px-4 py-3 text-xs">{TYPE_LABELS[report.type]}</td>
                <td className="px-4 py-3 font-mono text-xs">{formatPeriod(report.periodStart, report.periodEnd)}</td>
                <td className="px-4 py-3 text-xs">{report.generatedBy.name}</td>
                <td className="px-4 py-3">
                  <div className="flex items-center gap-3">
                    <button
                      onClick={() => onView(report)}
                      className="text-xs text-primary hover:underline font-semibold"
                    >
                      View
                    </button>
                    <button
                      onClick={() => onDownload(report.id, 'pdf')}
                      className="text-xs text-primary hover:underline font-semibold"
                    >
                      Download PDF
                    </button>
                    <button
                      onClick={() => onDownload(report.id, 'excel')}
                      className="text-xs text-primary hover:underline font-semibold"
                    >
                      Download Excel
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
