'use client';

import { Modal } from '@/components/ui/modal';
import { Button } from '@/components/ui/button';

type ReportType = 'MONTHLY_QC_SUMMARY' | 'LOT_PERFORMANCE' | 'CORRECTIVE_ACTIONS' | 'EQUIPMENT';

interface SerializedReport {
  id: string;
  type: ReportType;
  periodStart: string;
  periodEnd: string;
  scope: Record<string, unknown>;
  s3Key: string | null;
  generatedById: string;
  generatedAt: string;
  generatedBy: { name: string };
}

interface ReportPreviewModalProps {
  report: SerializedReport;
  onClose: () => void;
  onDownload: (id: string, format: 'pdf' | 'excel') => void;
}

const TYPE_LABELS: Record<ReportType, string> = {
  MONTHLY_QC_SUMMARY: 'Monthly QC Summary',
  LOT_PERFORMANCE: 'Lot Performance',
  CORRECTIVE_ACTIONS: 'Corrective Actions',
  EQUIPMENT: 'Equipment',
};

function formatDate(iso: string) {
  const d = new Date(iso);
  return d.toLocaleDateString('pt-BR', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

export function ReportPreviewModal({ report, onClose, onDownload }: ReportPreviewModalProps) {
  return (
    <Modal open onClose={onClose} title="Report Preview" maxWidth="max-w-2xl">
      <div className="flex flex-col gap-5">
        <div className="grid grid-cols-2 gap-4">
          <div className="flex flex-col gap-0.5">
            <span className="text-xs font-semibold uppercase tracking-wider text-on-surface-variant">
              Type
            </span>
            <span className="text-sm text-on-surface">{TYPE_LABELS[report.type]}</span>
          </div>
          <div className="flex flex-col gap-0.5">
            <span className="text-xs font-semibold uppercase tracking-wider text-on-surface-variant">
              Generated At
            </span>
            <span className="text-sm text-on-surface">{formatDate(report.generatedAt)}</span>
          </div>
          <div className="flex flex-col gap-0.5">
            <span className="text-xs font-semibold uppercase tracking-wider text-on-surface-variant">
              Period
            </span>
            <span className="text-sm font-mono text-on-surface">
              {new Date(report.periodStart).toLocaleDateString('pt-BR')} –{' '}
              {new Date(report.periodEnd).toLocaleDateString('pt-BR')}
            </span>
          </div>
          <div className="flex flex-col gap-0.5">
            <span className="text-xs font-semibold uppercase tracking-wider text-on-surface-variant">
              Generated By
            </span>
            <span className="text-sm text-on-surface">{report.generatedBy.name}</span>
          </div>
        </div>

        <div className="border border-border rounded bg-surface-variant p-6 flex items-center justify-center min-h-[200px]">
          <span className="text-sm text-on-surface-variant font-mono">
            PDF Preview — report-{report.id.slice(0, 8)}.pdf
          </span>
        </div>

        <div className="flex items-center justify-end gap-3 pt-2 border-t border-border">
          <Button variant="primary" size="sm" onClick={() => onDownload(report.id, 'pdf')}>
            Download PDF
          </Button>
          <Button variant="outline" size="sm" onClick={() => onDownload(report.id, 'excel')}>
            Download Excel
          </Button>
        </div>
      </div>
    </Modal>
  );
}
